// The website's words in English, Dutch and Arabic. Every language has exactly the keys of
// English: the type checker enforces it. Where the website names something the app also names
// (log in, layout, look, the prayer moments, …), it uses the app's own words
// (web/shared/app-i18n.ts); test/unit/site-page.test.ts keeps them in step.
// The prayer cards on the demo screens use the caption page's own labels (web/shared/i18n.ts).
import type { SiteLang } from "./khutbah.js";

type CaptionPageLang = "en" | "nl";

const en = {
  title: "Live khutbah translation for mosque screens · Turjuman",
  desc: "The Friday khutbah, lessons and talks, translated live on your mosque's TV or projector. 60 languages. Free and open source.",
  skip: "Skip to content",
  navLabel: "Main",
  langLabel: "Language",
  nav1: "How it works",
  nav2: "Self-host",
  login: "Log in",
  start: "Start free",
  lead: "Live translation of the Friday khutbah, on every screen in your mosque. It works the same for lessons and talks.",
  t1: "Free and open source (MIT)",
  t2: "Your own keys, stored encrypted",
  cta1: "Start for free",
  cta2: "Run it yourself",
  boardLabel: "A simulated Friday on a mosque screen, from the Athan to the Salah.",
  scrub: "Simulation timeline",
  sim: "Simulation",
  motionPause: "Pause animations",
  motionPlay: "Play animations",
  m_athan: "Athan",
  m_khutbah: "Khutbah",
  m_iqama: "Iqama",
  m_salah: "Salah",
  obs_h: "Works with what you already use.",
  obs_p:
    "Every screen is a web page. Show it on a TV, in OBS Studio, or in any tool that can display the web.",
  obs_alt: "One web page, shown on a TV, in OBS Studio and on a projector",
  obs_tv: "TV · browser",
  obs_obs: "OBS Studio · browser source",
  obs_pj: "Projector · any browser",
  cus_h: "Your screens, your style.",
  cus_p:
    "Ten ready-made looks, or fine-tune every colour, font and size and save your own. Full-screen or as an OBS overlay.",
  cus_look: "Look",
  cus_size: "Text size",
  cus_layout: "Layout",
  cd_preview: "Caption preview",
  cd_blocks: "Blocks",
  cd_rolling: "Rolling",
  cd_src: "Arabic text",
  cd_quran: "Quran in Arabic",
  cd_behind: "Behind",
  cd_cam: "Camera picture",
  cd_black: "Black",
  cd_white: "White",
  cd_tr: "Transparent",
  q_h: "Verses, with a verified reference.",
  q_p: "When the imam recites, Turjuman recognises the verse and adds its reference, checked against the Quran text. In Dutch it shows an approved translation.",
  det_h: "Athan, Iqama and Salah, recognised.",
  det_p:
    "Turjuman hears the Athan and the Iqama and switches every screen by itself. During Salah the captions rest. One tap overrides it.",
  moments: "Prayer",
  start_h: "Two ways to start.",
  acc_h: "Create an account",
  acc_p: "Add your Soniox key; we store it encrypted. Your first screen is ready in a few minutes.",
  enc: "Stored encrypted",
  self_h: "Run it yourself",
  self_p: "Clone the code and run it on your own computer or server.",
  copy: "Copy",
  copied: "Copied",
  f1: "MIT licence",
  f2: "Source on GitHub",
  f3: "Keys encrypted at rest",
  f4: "Runs on your own server",
  menu: "Menu",
  footLabel: "All pages",
  pg_screen: "Show on a screen",
  pg_security: "Security",
  pg_self: "Overview",
  pg_install: "Install",
  pg_network: "Phone & network",
  pg_docker: "Docker",
  pg_commands: "Commands",
  reportSec: "Report a security problem",
  privacy: "Privacy",
  contact: "Contact",
  quranCredit:
    "Quran text: Tanzil.net (CC BY 3.0). Verse translations on this site: Siregar (Dutch), Saheeh International (English).",
  stepperLabel: "Self-host, step by step",
  pagerLabel: "Previous and next",
  onThisPage: "On this page",
  prev: "Previous",
  next: "Next",
  allOptions: "All options",
  stepsObs: "Steps for OBS",
  stepByStep: "Step by step",
  freeU: "Free for the ummah.",
};

export type SiteKey = keyof typeof en;
export type Dict = Readonly<Record<SiteKey, string>>;

const nl: Dict = {
  title: "Live vertaling van de khutbah in je moskee · Turjuman",
  desc: "De vrijdagpreek (khutbah), lessen en lezingen, live vertaald op de tv of beamer in je moskee. 60 talen. Gratis en open source.",
  skip: "Direct naar de inhoud",
  navLabel: "Hoofdmenu",
  langLabel: "Taal",
  nav1: "Hoe het werkt",
  nav2: "Zelf hosten",
  login: "Inloggen",
  start: "Gratis starten",
  lead: "Live vertaling van de vrijdagkhutbah, op elk scherm in je moskee. Het werkt net zo voor lessen en lezingen.",
  t1: "Gratis en open source (MIT)",
  t2: "Je eigen sleutels, versleuteld opgeslagen",
  cta1: "Gratis beginnen",
  cta2: "Zelf hosten",
  boardLabel: "Een gesimuleerde vrijdag op een moskeescherm, van de Athan tot de Salah.",
  scrub: "Tijdlijn van de simulatie",
  sim: "Simulatie",
  motionPause: "Animaties pauzeren",
  motionPlay: "Animaties afspelen",
  m_athan: "Athan",
  m_khutbah: "Khutbah",
  m_iqama: "Iqama",
  m_salah: "Salah",
  obs_h: "Werkt met wat je al gebruikt.",
  obs_p:
    "Elk scherm is een webpagina. Toon het op een tv, in OBS Studio of in elk programma dat het web kan weergeven.",
  obs_alt: "Eén webpagina, getoond op een tv, in OBS Studio en op een beamer",
  obs_tv: "Tv · browser",
  obs_obs: "OBS Studio · browserbron",
  obs_pj: "Beamer · elke browser",
  cus_h: "Jouw schermen, jouw stijl.",
  cus_p:
    "Tien kant-en-klare stijlen, of verfijn elke kleur, elk lettertype en elke maat en bewaar je eigen stijl. Schermvullend of als OBS-overlay.",
  cus_look: "Stijl",
  cus_size: "Tekstgrootte",
  cus_layout: "Indeling",
  cd_preview: "Voorbeeld van de ondertiteling",
  cd_blocks: "Blokken",
  cd_rolling: "Doorlopend",
  cd_src: "Tekst in het Arabisch",
  cd_quran: "Koran in het Arabisch",
  cd_behind: "Erachter",
  cd_cam: "Camerabeeld",
  cd_black: "Zwart",
  cd_white: "Wit",
  cd_tr: "Transparant",
  q_h: "Verzen, met een gecontroleerde verwijzing.",
  q_p: "Als de imam reciteert, herkent Turjuman het vers en voegt de verwijzing toe, gecontroleerd aan de Korantekst. In het Nederlands toont het een erkende vertaling.",
  det_h: "Athan, Iqama en Salah, herkend.",
  det_p:
    "Turjuman hoort de Athan en de Iqama en schakelt elk scherm vanzelf om. Tijdens de Salah rust de ondertiteling. Met één tik stuur je het zelf.",
  moments: "Gebed",
  start_h: "Twee manieren om te beginnen.",
  acc_h: "Account maken",
  acc_p:
    "Voeg je Soniox-sleutel toe; we slaan hem versleuteld op. Je eerste scherm staat er binnen een paar minuten.",
  enc: "Versleuteld opgeslagen",
  self_h: "Zelf hosten",
  self_p: "Clone de code en draai het op je eigen computer of server.",
  copy: "Kopiëren",
  copied: "Gekopieerd",
  f1: "MIT-licentie",
  f2: "Broncode op GitHub",
  f3: "Sleutels versleuteld opgeslagen",
  f4: "Draait op je eigen server",
  menu: "Menu",
  footLabel: "Alle pagina's",
  pg_screen: "Op een scherm tonen",
  pg_security: "Beveiliging",
  pg_self: "Overzicht",
  pg_install: "Installeren",
  pg_network: "Telefoon & netwerk",
  pg_docker: "Docker",
  pg_commands: "Opdrachten",
  reportSec: "Een beveiligingsprobleem melden",
  privacy: "Privacy",
  contact: "Contact",
  quranCredit:
    "Korantekst: Tanzil.net (CC BY 3.0). Vertalingen van verzen op deze site: Siregar (Nederlands), Saheeh International (Engels).",
  stepperLabel: "Zelf hosten, stap voor stap",
  pagerLabel: "Vorige en volgende",
  onThisPage: "Op deze pagina",
  prev: "Vorige",
  next: "Volgende",
  allOptions: "Alle opties",
  stepsObs: "Stappen voor OBS",
  stepByStep: "Stap voor stap",
  freeU: "Gratis voor de ummah.",
};

const ar: Dict = {
  title: "ترجمة فورية لخطبة الجمعة على شاشات المسجد · ترجمان",
  desc: "خطبة الجمعة والدروس والمحاضرات، مترجمة فورًا على تلفاز مسجدك أو جهاز العرض. 60 لغة. مجاني ومفتوح المصدر.",
  skip: "انتقل إلى المحتوى",
  navLabel: "القائمة الرئيسية",
  langLabel: "اللغة",
  nav1: "كيف يعمل",
  nav2: "استضافة ذاتية",
  login: "تسجيل الدخول",
  start: "ابدأ مجانًا",
  lead: "ترجمة فورية لخطبة الجمعة، على كل شاشة في مسجدك. ويعمل ترجمان كذلك مع الدروس والمحاضرات.",
  t1: "مجاني ومفتوح المصدر (MIT)",
  t2: "مفاتيحك الخاصة، محفوظة ومشفّرة",
  cta1: "ابدأ مجانًا",
  cta2: "شغّله بنفسك",
  boardLabel: "محاكاة ليوم جمعة على شاشة المسجد، من الأذان إلى الصلاة.",
  scrub: "الخط الزمني للمحاكاة",
  sim: "محاكاة",
  motionPause: "إيقاف الحركة",
  motionPlay: "تشغيل الحركة",
  m_athan: "الأذان",
  m_khutbah: "الخطبة",
  m_iqama: "الإقامة",
  m_salah: "الصلاة",
  obs_h: "يعمل مع ما تستخدمه أصلًا.",
  obs_p:
    "كل شاشة هي صفحة ويب. اعرضها على تلفاز، أو في OBS Studio، أو في أي برنامج يعرض صفحات الويب.",
  obs_alt: "صفحة ويب واحدة، تُعرض على تلفاز وفي OBS Studio وعلى جهاز عرض",
  obs_tv: "تلفاز · متصفح",
  obs_obs: "OBS Studio · مصدر من نوع المتصفح",
  obs_pj: "جهاز عرض · أي متصفح",
  cus_h: "شاشاتك بأسلوبك.",
  cus_p:
    "عشرة أنماط جاهزة، أو اضبط كل لون وخط وحجم بدقة واحفظ نمطك الخاص. بملء الشاشة أو كطبقة في OBS.",
  cus_look: "النمط",
  cus_size: "حجم النص",
  cus_layout: "التخطيط",
  cd_preview: "معاينة الترجمة",
  cd_blocks: "كتل",
  cd_rolling: "سطور متتالية",
  cd_src: "النص الأصلي (العربية)",
  cd_quran: "القرآن بالعربية",
  cd_behind: "خلف الترجمة",
  cd_cam: "صورة الكاميرا",
  cd_black: "أسود",
  cd_white: "أبيض",
  cd_tr: "شفاف",
  q_h: "الآيات بمراجع موثّقة.",
  q_p: "حين يتلو الإمام آيةً، يتعرّف عليها ترجمان ويضيف مرجعها بعد مطابقته بنص القرآن. وبالهولندية يعرض ترجمة معتمدة.",
  det_h: "الأذان والإقامة والصلاة، تُعرَف تلقائيًا.",
  det_p:
    "يسمع ترجمان الأذان والإقامة فيبدّل كل الشاشات تلقائيًا، وتتوقف الترجمة أثناء الصلاة. ويمكنك التبديل يدويًا بلمسة واحدة.",
  moments: "الصلاة",
  start_h: "طريقتان للبدء.",
  acc_h: "أنشئ حسابًا",
  acc_p: "أضف مفتاح Soniox الخاص بك، ونحفظه لك مشفّرًا. وتكون شاشتك الأولى جاهزة خلال دقائق.",
  enc: "محفوظ ومشفّر",
  self_h: "شغّله بنفسك",
  self_p: "انسخ الشيفرة وشغّلها على حاسوبك أو خادمك.",
  copy: "نسخ",
  copied: "تم النسخ",
  f1: "رخصة MIT",
  f2: "الشيفرة على GitHub",
  f3: "المفاتيح محفوظة مشفّرة",
  f4: "يعمل على خادمك الخاص",
  menu: "القائمة",
  footLabel: "كل الصفحات",
  pg_screen: "عرض على شاشة",
  pg_security: "الأمان",
  pg_self: "نظرة عامة",
  pg_install: "التثبيت",
  pg_network: "الهاتف والشبكة",
  pg_docker: "Docker",
  pg_commands: "الأوامر",
  reportSec: "الإبلاغ عن مشكلة أمنية",
  privacy: "الخصوصية",
  contact: "تواصل معنا",
  quranCredit:
    "نص القرآن: Tanzil.net (CC BY 3.0). ترجمات الآيات في هذا الموقع: Siregar (الهولندية)، وSaheeh International (الإنجليزية).",
  stepperLabel: "الاستضافة الذاتية خطوة بخطوة",
  pagerLabel: "السابق والتالي",
  onThisPage: "في هذه الصفحة",
  prev: "السابق",
  next: "التالي",
  allOptions: "كل الخيارات",
  stepsObs: "خطوات OBS",
  stepByStep: "خطوة بخطوة",
  freeU: "مجاني للأمة.",
};

export const DICTS: Readonly<Record<SiteLang, Dict>> = { en, nl, ar };

/** The demo mosque screen's own words (its name and its live sign), in the language it shows: like
 *  the caption page, a screen speaks the language of its captions (English or Dutch). */
export const SCREEN_WORDS: Readonly<Record<CaptionPageLang, { hall: string; live: string }>> = {
  en: { hall: "Main hall", live: "Live" },
  nl: { hall: "Grote zaal", live: "Live" },
};
